// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAplsV6w7HLrSBOcx9Jb9w1bvDPvwoW-R8',
    appId: '1:102552482700:web:a798c67730683f3ee49ca9',
    messagingSenderId: '102552482700',
    projectId: 'employee-db-226dc',
    authDomain: 'employee-db-226dc.firebaseapp.com',
    storageBucket: 'employee-db-226dc.appspot.com',
    measurementId: 'G-7MSB2QGEJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUlDDT5oHWX4O7SKPpMD-3s4Mm20YVDEg',
    appId: '1:102552482700:android:2f11c025ff089fd8e49ca9',
    messagingSenderId: '102552482700',
    projectId: 'employee-db-226dc',
    storageBucket: 'employee-db-226dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzt8REOfCdw6Afw8mkWYOmAIlWp20PuUo',
    appId: '1:102552482700:ios:ac9102da84023f17e49ca9',
    messagingSenderId: '102552482700',
    projectId: 'employee-db-226dc',
    storageBucket: 'employee-db-226dc.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzt8REOfCdw6Afw8mkWYOmAIlWp20PuUo',
    appId: '1:102552482700:ios:ac9102da84023f17e49ca9',
    messagingSenderId: '102552482700',
    projectId: 'employee-db-226dc',
    storageBucket: 'employee-db-226dc.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAplsV6w7HLrSBOcx9Jb9w1bvDPvwoW-R8',
    appId: '1:102552482700:web:442cf18ad780de89e49ca9',
    messagingSenderId: '102552482700',
    projectId: 'employee-db-226dc',
    authDomain: 'employee-db-226dc.firebaseapp.com',
    storageBucket: 'employee-db-226dc.appspot.com',
    measurementId: 'G-3C0QSVK1Z3',
  );
}
